name = "" # todo
main = "build/worker/shim.mjs"
compatibility_date = "2022-01-20"

[vars]
WORKERS_RS_VERSION = "0.0.12"
LIBSQL_CLIENT_URL = "https://iku-turso-c1dde7bc-9cb0-11ed-bf07-8efdfa1d4e97-primary.fly.dev"
LIBSQL_CLIENT_USER = "psarna"
LIBSQL_CLIENT_PASS = "w25Si6nW37e9jY18"

[build]
command = "cargo install -q worker-build --version 0.0.7 && worker-build --release"
